[project]
version = "0.1.0"
name = "os"
cincludes = ["include"]
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
err = "*"
log = "*"
mem = "*"
symbols = "*"

[repos]
